fix Profit Switch error (+ high share diff advanced display)
This commit alongside with changes in node-stratum-pool/lib/pool.js
https://github.com/DeckerSU/node-stratum-pool/commit/d3dafec02cc566366c5bb043c115f0527eacd7fc
fixed this error when trying to switch Profit
Switch manually (node cli.js coinswitch komodo switch0)

clientsToRelinquish.forEach(function (cObj) {
TypeError: Cannot read property 'forEach' of null

Related info:

 - https://github.com/UNOMP/unified-node-open-mining-portal/issues/95#issuecomment-204865124 - this solution fixed it with crutches.
 - https://github.com/s-nomp/s-nomp/issues/125this commit